# Generated by Django 4.2.7 on 2025-06-30 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0005_alter_resourcemetadata_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('nlp_model_used', models.CharField(default='spacy_tfidf_hybrid', help_text='NLP model/approach used', max_length=50)),
                ('total_queries', models.PositiveIntegerField(default=0, help_text='Total queries in this session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('similarity_score', models.FloatField(blank=True, help_text='Combined similarity score', null=True)),
                ('tfidf_score', models.FloatField(blank=True, help_text='TF-IDF similarity score', null=True)),
                ('spacy_score', models.FloatField(blank=True, help_text='spaCy semantic similarity score', null=True)),
                ('keyword_score', models.FloatField(blank=True, help_text='Keyword matching score', null=True)),
                ('confidence_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('processed_query_length', models.PositiveIntegerField(blank=True, help_text='Length of processed query', null=True)),
                ('semantic_keywords_found', models.PositiveIntegerField(default=0, help_text='Number of semantic keywords extracted')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('matched_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAdmin.resourcemetadata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
