# Generated by Django 4.2.7 on 2025-06-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='keyword_score',
            field=models.FloatField(blank=True, help_text='Keyword matching score', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='processed_query_length',
            field=models.PositiveIntegerField(blank=True, help_text='Length of processed query', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='semantic_keywords_found',
            field=models.PositiveIntegerField(default=0, help_text='Number of semantic keywords extracted'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='spacy_score',
            field=models.FloatField(blank=True, help_text='spaCy semantic similarity score', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tfidf_score',
            field=models.FloatField(blank=True, help_text='TF-IDF similarity score', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='nlp_model_used',
            field=models.CharField(default='spacy_tfidf_hybrid', help_text='NLP model/approach used', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_queries',
            field=models.PositiveIntegerField(default=0, help_text='Total queries in this session'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Combined similarity score', null=True),
        ),
    ]
