# Generated by Django 4.2.7 on 2025-04-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.slug_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_title', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('forum_question', models.TextField()),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='user_bookmarked_forum', to=settings.AUTH_USER_MODEL)),
                ('commodity_id', models.ManyToManyField(related_name='forum_tag_commodity', to='appAdmin.commodity')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_forums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_forum',
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='appCmi.forumcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='appCmi.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_forum_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilteredCommodityFrequency',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(default=1)),
                ('date_filtered', models.DateField(default=django.utils.timezone.now)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.commodity')),
            ],
            options={
                'db_table': 'tbl_commodity_filtered',
            },
        ),
    ]
