# Generated by Django 4.2.7 on 2025-03-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_title', models.CharField(max_length=255)),
                ('forum_question', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='user_bookmarked_forum', to=settings.AUTH_USER_MODEL)),
                ('commodity_id', models.ManyToManyField(related_name='forum_tag_commodity', to='appAdmin.commodity')),
            ],
            options={
                'db_table': 'tbl_forum',
            },
        ),
    ]
