# Generated by Django 4.2.7 on 2025-03-18 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
        ('appCmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredCommodityFrequency',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(default=1)),
                ('date_filtered', models.DateField(default=django.utils.timezone.now)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.commodity')),
            ],
            options={
                'db_table': 'tbl_filtered_commodity',
            },
        ),
    ]
