# Generated by Django 4.2.7 on 2025-05-08 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('feedback', 'Feedback'), ('report', 'Report an Issue'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message to Admin',
                'verbose_name_plural': 'Messages to Admin',
                'db_table': 'tbl_message_to_admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
