# Generated by Django 4.2.7 on 2025-03-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0002_filteredcommodityfrequency'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filteredcommodityfrequency',
            table='tbl_commodity_filtered',
        ),
    ]
