# Generated by Django 4.2.7 on 2025-06-21 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.slug_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCmi', '0003_resourceview_resourcebookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_faq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_faq_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='faq_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appCmi.faq')),
            ],
            options={
                'db_table': 'tbl_faq_images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQTagAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='appCmi.faq')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_assignments', to='appCmi.faqtag')),
            ],
            options={
                'db_table': 'tbl_faq_tag_assignments',
                'unique_together': {('faq', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='FAQReaction',
            fields=[
                ('reaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='appCmi.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_faq_reactions',
                'unique_together': {('faq', 'user')},
            },
        ),
    ]
