# Generated by Django 4.2.7 on 2025-03-18 08:43

from django.db import migrations, models
import utils.slug_generator


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0003_alter_filteredcommodityfrequency_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
    ]
