# Generated by Django 4.2.7 on 2025-03-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0004_forum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
    ]
