# Generated by Django 4.2.7 on 2025-07-05 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCmi', '0004_faq_faqtag_faqimage_faqtagassignment_faqreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQView',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='appCmi.faq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_faq_views',
                'unique_together': {('faq', 'ip_address', 'session_key'), ('faq', 'user')},
            },
        ),
    ]
