# Generated by Django 4.2.7 on 2025-03-27 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0005_alter_forum_forum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
