# Generated by Django 4.2.7 on 2025-03-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0007_forumcomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forumcomment',
            table='tbl_forum_comment',
        ),
    ]
