# Generated by Django 4.2.7 on 2025-03-28 05:47

from django.db import migrations, models
import utils.slug_generator


class Migration(migrations.Migration):

    dependencies = [
        ('appCmi', '0009_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='slug',
            field=models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
    ]
