# Generated by Django 4.2.7 on 2025-03-28 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCmi', '0010_forumcomment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
