# Generated by Django 4.2.7 on 2025-03-18 08:43

import appAccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.CharField(default=appAccounts.models.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
    ]
