# Generated by Django 4.2.7 on 2025-04-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user-profiles/'),
        ),
    ]
