# Generated by Django 4.2.7 on 2025-04-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0002_alter_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_slug',
        ),
    ]
