# Generated by Django 4.2.7 on 2025-04-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import utils.slug_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_about',
            },
        ),
        migrations.CreateModel(
            name='AboutFooter',
            fields=[
                ('about_footer_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_footer', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_about_footer',
            },
        ),
        migrations.CreateModel(
            name='CMI',
            fields=[
                ('cmi_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('cmi_name', models.CharField(max_length=255)),
                ('cmi_meaning', models.CharField(max_length=255)),
                ('cmi_description', models.TextField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact_num', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cmi_image', models.ImageField(null=True, upload_to='cmi/')),
                ('status', models.CharField(default='active', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('url', models.URLField(null=True)),
                ('date_joined', models.DateField(null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tbl_cmi',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('commodity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resources_type', models.CharField(max_length=100)),
                ('commodity_img', models.ImageField(null=True, upload_to='commodities/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'tbl_commodity',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeResources',
            fields=[
                ('knowledge_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True)),
                ('knowledge_title', models.CharField(max_length=255)),
                ('knowledge_description', models.TextField()),
                ('status', models.CharField(default='active', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_knowledge_resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('event', 'Events'), ('info_system', 'Information Systems/Websites'), ('map', 'Maps'), ('media', 'Media'), ('news', 'News'), ('policy', 'Policies'), ('project', 'Projects'), ('publication', 'Publications'), ('technology', 'Technologies'), ('training', 'Training/Seminars'), ('webinar', 'Webinars'), ('product', 'Products')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('commodities', models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_commodities', to='appAdmin.commodity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_tag',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'db_table': 'tbl_about_video',
            },
        ),
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_title', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_useful_links',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('webinar_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('platform', models.CharField(max_length=100)),
                ('presenters', models.TextField()),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_webinar',
            },
        ),
        migrations.CreateModel(
            name='TrainingSeminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('trainers', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_seminar', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_training_seminar',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('patent_number', models.CharField(blank=True, max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_technology',
            },
        ),
        migrations.AddField(
            model_name='resourcemetadata',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_tags', to='appAdmin.tag'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('authors', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('report', 'Technical Report'), ('thesis', 'Thesis/Dissertation'), ('other', 'Other')], max_length=100)),
                ('publication_file', models.FileField(blank=True, null=True, upload_to='knowledge_resources/publications/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_publication',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255)),
                ('project_lead', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('terminated', 'Terminated')], max_length=50)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_project',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('technical_specifications', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_product',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField()),
                ('issuing_body', models.CharField(max_length=255)),
                ('policy_file', models.FileField(upload_to='knowledge_resources/policies/')),
                ('policy_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived')], max_length=50)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_policy',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('publication_date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='knowledge_resources/news_images/')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_news',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('presentation', 'Presentation')], max_length=50)),
                ('media_file', models.FileField(upload_to='knowledge_resources/media/')),
                ('media_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_media',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('map_file', models.FileField(upload_to='maps/')),
                ('map_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_map',
            },
        ),
        migrations.CreateModel(
            name='InformationSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('website_url', models.URLField()),
                ('system_owner', models.CharField(max_length=255)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information_system', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_information_system',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=utils.slug_generator.generate_random_slug, max_length=255, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('event_file', models.FileField(upload_to='knowledge_resources/events/')),
                ('is_virtual', models.BooleanField(default=False)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='appAdmin.resourcemetadata')),
            ],
            options={
                'db_table': 'tbl_knowledge_resources_event',
            },
        ),
    ]
