# Generated by Django 4.2.7 on 2025-03-18 06:23

from django.db import migrations, models
import utils.slug_generator


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmi',
            name='slug',
            field=models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='slug',
            field=models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgeresources',
            name='slug',
            field=models.CharField(default=utils.slug_generator.generate_random_slug, editable=False, max_length=12, unique=True),
        ),
    ]
