# Generated by Django 4.2.7 on 2025-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeresources',
            name='machine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
