# Generated by Django 4.2.7 on 2025-03-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0002_cmi_slug_commodity_slug_knowledgeresources_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='knowledgeresources',
            table='tbl_knowledge_resources',
        ),
    ]
