# Generated by Django 4.2.7 on 2025-03-19 07:32

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_alter_knowledgeresources_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'db_table': 'tbl_about_video',
            },
        ),
        migrations.AlterField(
            model_name='knowledgeresources',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
