# Generated by Django 4.2.7 on 2025-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_populate_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemetadata',
            name='commodities',
            field=models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_commodities', max_length=100, to='appAdmin.commodity'),
        ),
        migrations.AlterField(
            model_name='resourcemetadata',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='tbl_knowledge_resources_metadata_tags', max_length=100, to='appAdmin.tag'),
        ),
    ]
