# Generated by Django 4.2.7 on 2025-03-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_uploadvideo_alter_knowledgeresources_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmi',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='usefullinks',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
