# Generated by Django 4.2.7 on 2025-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_alter_resourcemetadata_commodities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemetadata',
            name='resource_type',
            field=models.CharField(choices=[('event', 'Events'), ('info_system', 'Information Systems/Websites'), ('map', 'Maps'), ('media', 'Media'), ('news', 'News'), ('policy', 'Policies'), ('project', 'Projects'), ('publication', 'Publications'), ('technology', 'Technologies'), ('training', 'Training/Seminars'), ('webinar', 'Webinars'), ('product', 'Products')], max_length=50),
        ),
    ]
